test_app_main_homepage:
    pattern:  /
    defaults: { _controller: TestAppMainBundle:Default:index }


test_app_main_conact:
    pattern: /{city}
    defaults: { _controller: TestAppMainBundle:Main:contact }


